### ISSUE TITLE
[Suggestion] Add shortcuts to open music player from directly within MusicControl

### ISSUE THREAD

**Issue by rainmakerV2** [mirobouma/MusicControl#8]
As the issue title suggests, I think it'd be neat if we could launch our media players (e.g. Spotify) from directly within MusicControl. 

It's a little clunky at the moment, having to first open Spotify from the Steam interface and then close it just to be able to control it via MusicControl. I am not sure if it's possible to have MusicControl open a media player in the background without taking the user away from whatever application they're currently in.

At any rate, I really love what you've done here, so if it stays in its current state, I'll be just fine!

Cheers

**Comment by rainmakerV2** [comment]
I see you touched on this in the past here: https://github.com/mirobouma/MusicControl/issues/2#issuecomment-1222373454

**Comment by mirobouma** [comment]
I've looked into this in the past in the `feat/test_flatpak_run` branch but unless we add new shortcuts like similar applications do, it seems hard to get the flatpaks to run in the background in game mode due to gamescope i assume. I don't have a lot of availability besides compatibility updates for the forseeable future so I will close this for the time being and re-open it if i have time in the future.
